# version format
version: 0.2.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - cmd: gem install sass
  - cmd: npm install -g grunt-cli
  - cmd: set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=7.7.0
  - cmd: cd BuildPackage
  - cmd: Build.bat

# to disable automatic builds
build: off

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip